-- Script designated to populate tables with initial data.


-- populate table confirmedcases --------
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 1  ,'5/30/2019',  '5/5/2020'	,'5/5/2020'     ,'5/3/2020'	    ,'50s'	    ,'FEMALE'	,'CC'	                ,'Resolved'	,'NO',2260	,'Simcoe Muskoka District Health Unit'	            ,'15 Sperling Drive'	            ,'Barrie' 	    ,'L4M 6K9'	,'www.simcoemuskokahealth.org'	                            ,44.41071258	,-79.68630597 );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 2  ,'11/20/2019', '10/21/2020' ,'11/21/2020'   ,'11/20/2019'	,'20s'	    ,'FEMALE'	,'NO KNOWN EPI LINK'	,'Resolved'	,'NO',4913	,'Southwestern Public Health'	                    ,'1230 Talbot Street'	            ,'St. Thomas'	,'N5P 1G9'	,'www.swpublichealth.ca'                                    ,42.77780366	,-81.15115646 );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 3  ,'1/1/2020',   '4/24/2020'	,'4/24/2020'	,'4/23/2020'	,'80s'	    ,'MALE'	    ,'NO KNOWN EPI LINK'	,'Resolved'	,'NO',2234	,'Haldimand-Norfolk Health Unit'	                ,'12 Gilbertson Drive'	            ,'Simcoe'	    ,'N3Y 4N5'	,'www.hnhu.org'	                                            ,42.84782526	,-80.30381491 );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 4  ,'1/1/2020',   '5/17/2020'	,'5/17/2020'	,'5/15/2020'	,'50s'	    ,'MALE'	    ,'CC'	                ,'Resolved'	,'NO',2265	,'Region of Waterloo, Public Health'	            ,'99 Regina Street South'	        ,'Waterloo'	    ,'N2J 4V3'	,'www.regionofwaterloo.ca'	                                ,43.46287573	,-80.52091315 );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 5  ,'1/1/2020',   '5/26/2021'	,'3/31/2021'	,'3/28/2021'	,'UNKNOWN'	,'MALE'	    ,'TRAVEL'	            ,'Resolved'	,'NO',2263	,'Timiskaming Health Unit'	                        ,'247 Whitewood Avenue, Unit 43'	,'New Liskeard'	,'P0J 1P0'	,'www.timiskaminghu.com'	                                ,47.5092835	    ,-79.681632   );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 6  ,'1/5/2020',   '1/9/2021'	,'1/8/2021'	    ,'1/7/2021'	    ,'20s'	    ,'MALE'	    ,'NO KNOWN EPI LINK'	,'Resolved'	,'NO',2251	,'Ottawa Public Health'                             ,'100 Constellation Drive'	        ,'Ottawa'	    ,'K2G 6J8'	,'www.ottawapublichealth.ca'	                            ,45.3456651	    ,-75.7639122  );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 7  ,'1/10/2020',  '6/10/2020'	,'6/10/2020'	,'6/9/2020'	    ,'50s'	    ,'MALE'	    ,'CC'	                ,'Resolved'	,'NO',2234	,'Haldimand-Norfolk Health Unit'	                ,'12 Gilbertson Drive'	            ,'Simcoe'	    ,'N3Y 4N5'	,'www.hnhu.org'	                                            ,42.84782526	,-80.30381491 );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 8  ,'1/13/2020',  '1/23/2021'	,'1/23/2021'	,'1/22/2021'	,'30s'	    ,'MALE'	    ,'NO KNOWN EPI LINK'	,'Resolved'	,'NO',2260	,'Simcoe Muskoka District Health Unit'	            ,'15 Sperling Drive'                ,'Barrie'	    ,'L4M 6K9'	,'www.simcoemuskokahealth.org'	                            ,44.41071258	,-79.68630597 );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 9  ,'1/16/2020',  '10/8/2020'	,'10/8/2020'	,'10/6/2020'	,'50s'	    ,'FEMALE'	,'NO KNOWN EPI LINK'	,'Resolved'	,'NO',2258	,'Eastern Ontario Health Unit'	                    ,'1000 Pitt Street'	                ,'Cornwall'	    ,'K6J 5T1'	,'www.eohu.ca'	                                            ,45.02915233	,-74.73629779 );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 10 ,'1/21/2020',   '1/23/2020'	,'1/26/2020'	,'1/23/2020'	,'50s'	    ,'MALE'	    ,'TRAVEL'	            ,'Resolved'	,'NO',3895	,'Toronto Public Health'	                        ,'277 Victoria Street, 5th Floor'	,'Toronto'	    ,'M5B 1W2'	,'www.toronto.ca/community-people/health-wellness-care/'	,43.65659125	,-79.37935801 );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 11 ,'1/22/2020',   '1/23/2020'	,'1/27/2020'	,'1/25/2020'	,'50s'	    ,'FEMALE'	,'TRAVEL'	            ,'Resolved'	,'NO',3895	,'Toronto Public Health'	                        ,'277 Victoria Street, 5th Floor'	,'Toronto'	    ,'M5B 1W2'	,'www.toronto.ca/community-people/health-wellness-care/'	,43.65659125	,-79.37935801 );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 12 ,'1/22/2020',   '10/24/2020','10/24/2020'   ,'1/22/2020'	,'20s'	    ,'FEMALE'	,'NO KNOWN EPI LINK'	,'Resolved'	,'NO',3895	,'Toronto Public Health'	                        ,'277 Victoria Street, 5th Floor'	,'Toronto'	    ,'M5B 1W2'	,'www.toronto.ca/community-people/health-wellness-care/'	,43.65659125	,-79.37935801 );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 13 ,'1/24/2020',   '1/24/2020'	,'2/4/2020'	    ,'1/24/2020'	,'20s'	    ,'FEMALE'	,'TRAVEL'	            ,'Resolved'	,'NO',2244	,'Middlesex-London Health Unit'	                    ,'50 King Street'	                ,'London'	    ,'N6A 5L7'	,'www.healthunit.com'	                                    ,42.98146842	,-81.25401572 );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 14 ,'1/25/2020',   '1/27/2021'	,'1/27/2021'	,'1/26/2021'	,'20s'	    ,'MALE'	    ,'CC'	                ,'Resolved'	,'NO',2265	,'Region of Waterloo, Public Health'	            ,'99 Regina Street South'	        ,'Waterloo'	    ,'N2J 4V3'	,'www.regionofwaterloo.ca'	                                ,43.46287573	,-80.52091315 );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 15 ,'1/27/2020',   '2/13/2021'	,'2/13/2021'	,'2/12/2021'	,'60s'	    ,'MALE'	    ,'NO KNOWN EPI LINK'	,'Resolved'	,'NO',3895	,'Toronto Public Health'	                        ,'277 Victoria Street, 5th Floor'	,'Toronto'	    ,'M5B 1W2'	,'www.toronto.ca/community-people/health-wellness-care/'	,43.65659125	,-79.37935801 );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 16 ,'1/29/2020',   '1/27/2021'	,'1/27/2021'	,'1/26/2021'	,'20s'	    ,'FEMALE'	,'OB'	                ,'Resolved'	,'Yes',2265	,'Region of Waterloo, Public Health'	            ,'99 Regina Street South'	        ,'Waterloo'	    ,'N2J 4V3'	,'www.regionofwaterloo.ca'	                                ,43.46287573	,-80.52091315 );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 17 ,'1/31/2020',   '7/24/2020'	,'7/24/2020'	,'7/24/2020'	,'30s'	    ,'FEMALE'	,'NO KNOWN EPI LINK'	,'Resolved'	,'NO',2253	,'Peel Public Health'	                            ,'7120 Hurontario Street'	        ,'Mississauga'	,'L5W 1N4'	,'www.peelregion.ca/health/'	                            ,43.6474713	    ,-79.7088933  );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 18 ,'2/1/2020',    '4/14/2020'	,'4/16/2020'	,'4/14/2020'	,'60s'	    ,'FEMALE'	,'TRAVEL'	            ,'Resolved'	,'NO',2238	,'Hastings and Prince Edward Counties Health Unit'	,'179 North Park Street'            ,'Belleville'	,'K8P 4P1'	,'www.hpePublicHealth.ca'	                                ,44.18667362	,-77.39144554 );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 19 ,'2/2/2020',    '3/13/2020'	,'3/12/2020'	,'3/12/2020'	,'20s'	    ,'MALE'	    ,'CC'	                ,'Resolved'	,'NO',2253	,'Peel Public Health'	                            ,'7120 Hurontario Street'	        ,'Mississauga'	,'L5W 1N4'	,'www.peelregion.ca/health/'	                            ,43.6474713	    ,-79.7088933  );
INSERT INTO confirmedcases (Row_ID, Accurate_Episode_Date, Case_Reported_Date, Test_Reported_Date, Specimen_Date, Age_Group, Client_Gender, Case_AcquisitionInfo, Outcome1, Outbreak_Related, Reporting_PHU_ID, Reporting_PHU, Reporting_PHU_Address, Reporting_PHU_City, Reporting_PHU_Postal_Code, Reporting_PHU_Website, Reporting_PHU_Latitude, Reporting_PHU_Longitude)
VALUES ( 20 ,'2/5/2020',    '2/21/2020'	,'2/24/2020'	,'2/22/2020'	,'20s'	    ,'FEMALE'	,'TRAVEL'	            ,'Resolved'	,'NO',3895	,'Toronto Public Health'	                        ,'277 Victoria Street, 5th Floor'	,'Toronto'	    ,'M5B 1W2'	,'www.toronto.ca/community-people/health-wellness-care/'	,43.65659125	,-79.37935801 );

-----------------

